### ISSUE TITLE
Multi-frame pipeline

### ISSUE THREAD

**Issue by scheibel** [cginternals/gloperate#160]
We want a pipeline that provides multi-frame rendering (as in GPU Pro 7) and operates on a subpipeline that is responsible for the actual rendering.

Concept features:
- [x] Frame aggregation #183 
- [x] Frame reset #183

CG features:
- [x] Subpixel anti-aliasing (NDC offset) #183
- [ ] Soft shadows (light position offset)
- [x] Pixel-based transparency (transparency mask) #183
- [ ] Object-based transparency (transparency mask)
- [x] Depth-of-field (projection offset) #183

**Comment by sbusch42** [comment]
I think the concept itself is implemented now. Open separate issues for missing CG features and/or demo pipelines.
